services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: airport_api_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -uroot -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: airport_api_db
      DB_USER: appuser
      DB_PASSWORD: apppass
      PORT: 8080
    ports: ["8080:8080"]
